Repository r4ss/r4ss, pull requests merged in 2024-09, with the labels that each got.

#962 File comments to write time
  R/SS_writectl_3.30.R
  R/SS_writedat_3.30.R
  R/SS_writeforecast.R
  R/SS_writestarter.R
  R/helper_fxns.R
  man/SS_writectl_3.30.Rd
  man/add_file_header.Rd
  man/writeComment.Rd
Labels: bug, SS_read/SS_write

#961 Change figure names in plots to have better latex compatibility
  R/SSplotCatch.R
  R/SSplotComps.R
  R/SSplotIndices.R
Labels: plots

#960 Smarter profile.label for profile plots
  R/SSplotProfile.R
  inst/WORDLIST
  man/SSplotProfile.Rd
Labels: plots

#966 Add summary biomass to SSsummarize() and SSplotComparisons()
  R/SSplotComparisons.R
  R/SSsummarize.R
  R/run.R
  man/SSplotComparisons.Rd
  tests/testthat/test-basics.R
  tests/testthat/test-older_ss3.R
  vignettes/r4ss-intro-vignette.Rmd
Labels: plots, output

#968 add SpawnOutputLabel element to list created by SS_output() for use in figures and tables
  R/NegLogInt_Fn.R
  R/SS_Sensi_plot.R
  R/SS_fitbiasramp.R
  R/SS_html.R
  R/SS_output.R
  R/SS_plots.R
  R/SS_read_summary.R
  R/SS_varadjust.R
  R/SS_writectl_3.24.R
  R/SS_writedat_3.24.R
  R/SS_writedat_3.30.R
  R/SS_writeforecast.R
  R/SS_writestarter.R
  R/SS_writewtatage.R
  R/SSbiologytables.R
  R/SSexecutivesummary.r
  R/SSgetoutput.R
  R/SSmakeMmatrix.R
  R/SSplotAgeMatrix.R
  R/SSplotBiology.R
  R/SSplotCatch.R
  R/SSplotComparisons.R
  R/SSplotComps.R
  R/SSplotData.R
  R/SSplotDiscard.R
  R/SSplotDynamicB0.R
  R/SSplotRecdevs.R
  R/SSplotSPR.R
  R/SSplotSpawnrecruit.R
  R/SSplotTimeseries.R
  R/SSplotYield.R
  R/SSsummarize.R
  R/SSunavailableSpawningOutput.R
  R/TSCplot.R
  R/bubble3.R
  R/helper_fxns.R
  R/make_multifig.R
  R/profile.R
  man/SS_output.Rd
  man/SS_plots.Rd
  man/SSplotAgeMatrix.Rd
  man/SSplotBiology.Rd
  man/SSplotCatch.Rd
  man/SSplotComps.Rd
  man/SSplotDynamicB0.Rd
  man/SSplotSpawnrecruit.Rd
  man/SSplotTimeseries.Rd
  man/SSplotYield.Rd
Labels: plots, output
